spring.application.name=inventario

# Puerto (Render lo asigna automáticamente)
server.port=${PORT:8080}

# ==========================
# BASE DE DATOS
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.defer-datasource-initialization=true

# ==========================
# THYMELEAF
# ==========================
spring.thymeleaf.cache=false